In file included from [01m[K/home/rsa2021/py_pub_sub/src/zbar_ros/include/zbar_ros/barcode_reader_node.hpp:35[m[K,
                 from [01m[K/home/rsa2021/py_pub_sub/src/zbar_ros/src/barcode_reader_node.cpp:33[m[K:
[01m[K/home/rsa2021/py_pub_sub/src/zbar_ros/include/zbar_ros/./zbar.h:1301:11:[m[K [01;31m[Kfatal error: [m[Kzbar/Exception.h: No such file or directory
 1301 | # include [01;31m[K"zbar/Exception.h"[m[K
      |           [01;31m[K^~~~~~~~~~~~~~~~~~[m[K
compilation terminated.
make[2]: *** [CMakeFiles/barcode_reader_node.dir/build.make:63: CMakeFiles/barcode_reader_node.dir/src/barcode_reader_node.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:80: CMakeFiles/barcode_reader_node.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
